# Generated by Django 5.0.3 on 2024-04-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.CharField(max_length=19),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expiration_date',
            field=models.CharField(max_length=10),
        ),
    ]
