# Generated by Django 5.0.3 on 2024-04-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_payment_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='service',
            name='servicing_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
